//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerHandHistory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokerHandHistory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand #53005191 - Holdem(No Limit) - $0.01/$0.02 - 2019/05/22 04:41:53 UTC
        ///Agoura Hills 6-max Seat #5 is the button
        ///Seat 1: IgUdf1rh ($2.00)
        ///Seat 2: ROI_RUINER ($2.00)
        ///Seat 3: MasGuap ($0.77)
        ///Seat 4: Gorillosaur ($2.76)
        ///Seat 5: D. DeGraaf ($1.86)
        ///IgUdf1rh posts the small blind $0.01
        ///ROI_RUINER posts the big blind $0.02
        ///*** HOLE CARDS ***
        ///Dealt to ROI_RUINER [Ks 9c]
        ///MasGuap folds
        ///Gorillosaur folds
        ///D. DeGraaf raises $0.05 to $0.05
        ///IgUdf1rh folds
        ///ROI_RUINER calls $0.03
        ///*** FLOP *** [6d Kh Ad]
        ///M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Agoura_Hills_Hand_53005191 {
            get {
                return ResourceManager.GetString("Agoura_Hills_Hand_53005191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerStars Hand #161248135942: Tournament #1724073465, $0.44+$0.06 USD Hold&apos;em No Limit - Level I (10/20) - 2016/11/11 17:24:28 BRT [2016/11/11 14:24:28 ET]
        ///Table &apos;1724073465 1&apos; 9-max Seat #1 is the button
        ///Seat 1: Realdyralei (1500 in chips) 
        ///Seat 2: johntheslon (1500 in chips) 
        ///Seat 3: cbill_gr (1500 in chips) 
        ///Seat 4: prizrak play (1500 in chips) 
        ///Seat 5: wisg33 (1500 in chips) 
        ///Seat 6: leo.criv (1500 in chips) 
        ///Seat 7: walerson47 (1500 in chips) 
        ///Seat 8: Luiz F. 1977 (1500 in chips) 
        ///Seat 9: Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pokerstars_Hand_161248135942 {
            get {
                return ResourceManager.GetString("Pokerstars_Hand_161248135942", resourceCulture);
            }
        }
    }
}
